# Generated by Django 4.1.2 on 2022-12-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_test_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='nomer',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
