# Generated by Django 4.1.2 on 2022-12-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='worker',
            field=models.CharField(choices=[('AR', 'Архитектор'), ('KR', 'Конструктор'), ('DZ', 'Дизайнер')], max_length=300),
        ),
    ]
