# Generated by Django 4.1.2 on 2022-12-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_doljn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doljn',
            name='title',
        ),
        migrations.AddField(
            model_name='doljn',
            name='Doldjnost',
            field=models.CharField(choices=[('AR', 'Архитектор'), ('KR', 'Конструктор'), ('DZ', 'Дизайнер')], default='Архитектор', max_length=255),
        ),
    ]
