# Generated by Django 4.1.3 on 2023-01-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('architect', 'Архитектор'), ('constructor', 'Конструктор'), ('designer', 'Дизайнер')], max_length=20),
        ),
    ]
