# Generated by Django 4.1.3 on 2023-01-28 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_profile_position'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
