# Generated by Django 4.1.3 on 2023-01-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('architect', 'architect'), ('constructor', 'constructor'), ('designer', 'designer')], max_length=50),
        ),
    ]
