# Generated by Django 4.1.3 on 2023-01-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_profile_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.CharField(choices=[('Архитектор', 'архитектор'), ('Дизайнер', 'дизайнер'), ('Конструктор', 'конструктор')], max_length=20),
        ),
    ]
