# Generated by Django 4.1.3 on 2023-01-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_userprofile_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('Архитектор', 'architect'), ('Конструктор', 'constructor'), ('Дизайнер', 'designer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.CharField(choices=[('architect', 'архитектор'), ('designer', 'дизайнер'), ('constructor', 'конструктор')], max_length=20),
        ),
    ]
