# Generated by Django 4.1.2 on 2022-12-14 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_task_nomer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='nomer',
        ),
    ]
