# Generated by Django 4.1.2 on 2022-12-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_task_nomer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker', models.CharField(choices=[('AR', 'Архитектор'), ('KR', 'Конструктор'), ('DZ', 'Дизайнер'), ('RU', 'Russia'), ('IT', 'Italy')], max_length=300)),
            ],
        ),
    ]
