# Generated by Django 4.1.2 on 2022-12-20 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_role_worker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
